[book]
authors = ["Vito Van"]
language = "en"
multilingual = false
src = "src"
title = "CALM - a Lisp development kit"

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/VitoVan/calm"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/VitoVan/calm/edit/main/docs/{path}"
