name: CI

on: push

jobs:

  Linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Build for Linux
        run: |
          docker run --env CI=true -v $PWD:/calm -w /calm fedora:32 bash build/build.sh
          ls -lah .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CALM Linux
          if-no-files-found: error
          path: |
            *.tgz

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            *.tgz
