name: EXAMPLE

on:
  push:
    tags:
      - "*.*.*"
      - "test-calm-*"

jobs:

  ZIP:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compress Examples
        run: |
          cd docs/src/
          zip -r examples.zip examples
          mv examples.zip ../../
          cd ../../
          ls -lah .
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          prerelease: true
          files: |
            *.zip
