name: SBCL

on:
  push:
    tags:
      - "sbcl-*"
      - "test-sbcl-*"

jobs:

  Ubuntu:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          sudo apt update -y
          sudo apt install build-essential -y
          sudo apt install libzstd-dev -y
      - name: build
        run: |
          # use custom built sbcl for grandpa ubuntu
          # otherwise, it won't build
          curl -o install_root.zip -L https://github.com/VitoVan/calm/releases/download/sbcl-2.3.4/install_root-ubuntu-20.04.zip
          unzip install_root.zip
          rm install_root.zip
          mv ./install_root ./sbcl
          export PATH=$(pwd)/sbcl/bin:$PATH
          # start building new sbcl
          set -x
          curl -OL http://downloads.sourceforge.net/project/sbcl/sbcl/2.4.7/sbcl-2.4.7-source.tar.bz2
          set +x
          bzip2 -cd sbcl-2.4.7-source.tar.bz2 | tar xvf -
          cd sbcl-2.4.7
          sh make.sh --with-sb-thread --with-sb-core-compression
      - name: zip install_root
        run: |
          set -x
          cd sbcl-2.4.7
          export INSTALL_ROOT=$HOME/install_root
          sh install.sh
          cd ..
          echo $INSTALL_ROOT
          cp -r $INSTALL_ROOT ./install_root
          zip -r -9 install_root-${{ matrix.os }}.zip ./install_root
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          files: |
            *.zip

  macOS:

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-12, macos-13, macos-14]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install
        shell: bash
        run: |
          brew update && brew install sbcl && brew fetch zstd && brew reinstall zstd
      - name: build
        run: |
          # for newer version of homebrew, the location of files has changed
          export CPATH=$(brew --prefix zstd)/include:/usr/local/include:$CPATH
          export LIBRARY_PATH=$(brew --prefix zstd)/lib/:$LIBRARY_PATH
          # start building
          set -x
          curl -OL http://downloads.sourceforge.net/project/sbcl/sbcl/2.4.7/sbcl-2.4.7-source.tar.bz2
          set +x
          bzip2 -cd sbcl-2.4.7-source.tar.bz2 | tar xvf -
          cd sbcl-2.4.7
          sh make.sh --with-sb-thread --with-sb-core-compression
      - name: zip install_root
        run: |
          set -x
          cd sbcl-2.4.7
          export INSTALL_ROOT=$HOME/install_root
          sh install.sh
          cd ..
          echo $INSTALL_ROOT
          cp -r $INSTALL_ROOT ./install_root
          zip -r -9 install_root-${{ matrix.os }}.zip ./install_root

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          files: |
            *.zip

  Windows:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019]

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        with:
          location: D:\
          release: true
          update: false
          install: >-
            p7zip
            zip
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-zstd
            make
            diffutils
            wget
            git
      - name: build
        run: |
          wget http://prdownloads.sourceforge.net/sbcl/sbcl-2.2.7-x86-64-windows-binary.msi
          7z x sbcl-2.2.7-x86-64-windows-binary.msi -Osbcl-2.2.7-bin && rm sbcl-2.2.7-x86-64-windows-binary.msi
          wget http://downloads.sourceforge.net/project/sbcl/sbcl/2.4.7/sbcl-2.4.7-source.tar.bz2
          bzip2 -cd sbcl-2.4.7-source.tar.bz2 | tar xvf -
          cd sbcl-2.4.7
          PATH=$PATH:"../sbcl-2.2.7-bin/" SBCL_HOME="../sbcl-2.2.7-bin/" sh make.sh --xc-host='sbcl --lose-on-corruption --disable-ldb --disable-debugger' --with-sb-thread --with-sb-core-compression
      - name: zip install_root
        run: |
          set -x
          cd sbcl-2.4.7
          export INSTALL_ROOT=$HOME/install_root
          sh install.sh
          cd ..
          echo $INSTALL_ROOT
          cp -r $INSTALL_ROOT ./install_root
          zip -r -9 install_root-${{ matrix.os }}.zip ./install_root
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          files: |
            *.zip
